apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Chengcheng Ding\Documents\Srcs\docker-hadoop\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: datanode
  name: datanode
spec:
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
  selector:
    io.kompose.service: datanode
status:
  loadBalancer: {}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hadoop-datanode-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fsType: ext4