apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Chengcheng Ding\Documents\Srcs\docker-hadoop\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "50070"
      port: 50070
      targetPort: 50070
  selector:
    io.kompose.service: namenode
status:
  loadBalancer: {}
