apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Chengcheng Ding\Documents\Srcs\docker-hadoop\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nodemanager1
  name: nodemanager1
spec:
  ports:
    - name: "8042"
      port: 8042
      targetPort: 8042
  selector:
    io.kompose.service: nodemanager1
status:
  loadBalancer: {}
